setwd("D:/Hackathon/relationship/SAR")
df<- read.csv("mprship.csv")
summary(df)
reger <-lm(num~income, df)
reg1<-lm(num~humidity + aqi, df)
reg2 <-lm(num~humidity+aqi+GDP,df)
reg3<-lm(num~humidity+aqi+GDP+GR, df)
reg4<-lm(num~humidity+GR+aqi+GDP+temperature,df)
reg <- lm(num~GR+ GDP+ humidity+ aqi + temperature+rainfall+Oldpop, df)
regopt <- lm(num~GR+ GDP+ humidity+ aqi +temperature+rainfall+Oldpop, df) #+ Grth.rt+ gdp + humidity + aqi + Temperature+Rainfall
reg5<-lm(num~rainfall+humidity+aqi+temperature+GDP+GR,df)
coefficients(reg)
summary(reg)
summary(reg1)
summary(reg2)
summary(reg3)
summary(reg4)
summary(reg5)
summary(regopt)
summary(reger)
AIC(reger)
AIC(reg5)
AIC(regopt)
AIC(reg)
AIC(reg1)
AIC(reg3)
AIC(reg4)
vif(reg)
vif(reg1)
vif(reg2)
vif(reg3)
vif(reg4)
vif(regopt)
vif(reger)
vif(reg5)

